# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

```{r, echo=FALSE, out.width='90%', fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'png', fig.cap='Some caption.'}

# \begin{tikzpicture}[scale=.7]
# \draw [fill=gray!30,very thick] (0,-1) rectangle (5,1);
# \draw [very thick] (5, 0) -- (13,0);
# \node [below] at (2,-1) {\large Hello};
# \node [below, align=center] at (0,-1) {\large Two\\ lines};
# \end{tikzpicture}


```

```{r,echo=FALSE,engine='tikz',fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'png'}
  
\begin{tikzpicture}[scale=.7]
\draw [fill=gray!30,very thick] (0,-1) rectangle (5,1);
\draw [very thick] (5, 0) -- (13,0);
\node [below] at (2,-1) {\large Hello};
\node [below, align=center] at (0,-1) {\large Two\\ lines};
\end{tikzpicture}
```

## Example two

```{r,echo=FALSE,engine='tikz',fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'png'}

\begin{tikzpicture}
\draw[gray, thick] (-1,2) -- (2,-4);
\draw[gray, thick] (-1,-1) -- (2,2);
\filldraw[black] (0,0) circle (2pt) node[anchor=west]{Intersection point};
\end{tikzpicture}

```
